/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in active development, breaking changes may be made prior to official release of version 1.  **Important:** This library is in active development 
 *
 * API version: 0.0.1-rc
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// EscrowRequest struct for EscrowRequest
type EscrowRequest struct {
	// The cashaddress of the buyer
	BuyerAddr *interface{} `json:"buyerAddr"`
	// The cashaddress of the arbiter
	ArbiterAddr *interface{} `json:"arbiterAddr"`
	// The cashaddress of the seller
	SellerAddr *interface{} `json:"sellerAddr"`
}
