/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in active development, breaking changes may be made prior to official release of version 1.  **Important:** This library is in active development 
 *
 * API version: 0.0.1-rc
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// SendResponse struct for SendResponse
type SendResponse struct {
	// The hash of a transaction
	TxId string `json:"txId,omitempty"`
	Balance BalanceResponse `json:"balance,omitempty"`
}
