/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in active development, breaking changes may be made prior to official release of version 1.  **Important:** This library is in active development 
 *
 * API version: 0.0.2
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// WalletRequest struct for WalletRequest
type WalletRequest struct {
	// User defined string for wallet
	Name string `json:"name,omitempty"`
	// network type
	Network string `json:"network,omitempty"`
	// Wallet type, either a single wallet with private key (wif) or a Hierarchical Deterministic wallet determined from a seed.
	Type string `json:"type,omitempty"`
}
