/*
 * Mainnet Cash
 *
 * A developer friendly bitcoin cash wallet api  This API is currently in active development, breaking changes may be made prior to official release of version 1.  **Important:** This library is in active development 
 *
 * API version: 0.0.2
 * Contact: hello@mainnet.cash
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi
// ContractFnRequest struct for ContractFnRequest
type ContractFnRequest struct {
	// serialized contract 
	ContractId string `json:"contractId"`
	// ID that is returned in `wallet` field of /wallet call 
	WalletId string `json:"walletId"`
	// Action for finalization of contract.
	Action string `json:"action"`
	// getHexOnly (default:false), if true, will cause only the transaction hex to be returned; if false, the transaction will be sent to the network 
	GetHexOnly bool `json:"getHexOnly,omitempty"`
	UtxoIds []string `json:"utxoIds,omitempty"`
}
